### ISSUE TITLE
Not pulling data from Jenkins instance 

### ISSUE THREAD

**Issue by karthik120** [simplesurance/jenkins-exporter#3]
I had installed ur binary and tried to run it like below

./jenkins-exporter-linux_amd64 -jenkins-url <Jenkins URL> -jenkins-user=<MYID> -jenkins-password=<APi password> -jenkins-job-whitelist=<multi branch job name>

While the server starts, I don't see any entry related to jenkins job

**Comment by fho** [comment]
Sorry for the late response, I somehow missed the notification.

Did you invoked as you wrote?
If yes then the issue is that you specified empty values for those parameters.

If your jenkins server http would be: `https://myjenkins.com`, your jenkins user name: `karthik`, your password: `hacktheplanet`, you would have to invoke the binary like:
```sh
./jenkins-exporter-linux_amd64 -jenkins-url https://myjenkins.com -jenkins-user karthik -jenkins-password hacktheplanet
```
